import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import { logger } from 'hono/logger'
import { homeController } from '#/controllers/home'
import { workController } from '#/controllers/work'
import { appLayout } from '#/middleware/app-layout'
import { assetCache } from '#/middleware/asset-cache'
import '#/styles/main.css'

const app = new Hono()

/***************************************
 * Middleware
 ***************************************/

// built in middleware
app.use(logger())

// Assets are generated by Vite to the dist folder
app.use('/assets/*', assetCache, serveStatic({ root: './dist' }))

// Currently all the routes should have the same layout
app.use('*', appLayout)

/***************************************
 * Router
 ***************************************/

app.get('/', ...homeController)
app.get('/work', ...workController)

/***************************************
 * Server
 ***************************************/

export default {
  port: 3000,
  fetch: app.fetch,
}
